### ISSUE TITLE
Status icons do not show up iOS

### ISSUE THREAD

**Issue by jigahertz** [gilbN/MonitOrg#5]
When viewing the OrgV2 homepage from any browser on iOS, the status icons disappear and leave a gap of where they are supposed to be.

**Comment by gilbN** [comment]
Yeah. It's a monitorr issue. They're looking into it. 
https://github.com/Monitorr/Monitorr/issues/182

**Comment by seanvree** [comment]
is this still an issue @jigahertz @gilbN  ?

**Comment by gilbN** [comment]
Oh, forgot about this one. 

```
<div id="announcementRow" class="row"><h4 class="pull-left"><span>Monitorr</span></h4><hr class="hidden-xs"></div>
<div style="overflow:hidden; height:260px">
<iframe class="iframe" frameborder="0" src="https://monitorr.domain.com/index.min.php"></iframe>
</div>
```

This fixed it for me.

**Comment by seanvree** [comment]
@gilbN  so is it the `frameborder="0"` that did it?

**Comment by gilbN** [comment]
I didnt test what exactly was the issue but I think it's the `<embed style=`. This was discovered when [adding custom Grafana html in Org](https://technicalramblings.com/blog/spice-up-your-homepage-part-ii/) and it would reload the panels embedded when just switching between tabs. I also used `<embed style=` on that html. 

So when switching from embed style to iframe it fixed that and the issue that it wouldnt load on ios safari/webkit. 
``` 
<div style="overflow:hidden;  height:255px">    
        <embed style="height:100%" width='100%' src='https://yourdomain.com/monitorr/index.min.php'/>
</div>
<br>
```
To the one above

**Comment by seanvree** [comment]
humm, okay. thanks @gilbN

**Comment by gilbN** [comment]
No problem.
